# Generated by Django 5.2.1 on 2025-05-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0002_doctor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
