# Generated by Django 5.2.1 on 2025-05-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0003_authority_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
