# Generated by Django 5.2.1 on 2025-05-11 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0004_authority_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authority',
            old_name='zipcode',
            new_name='postal_code',
        ),
    ]
