# Generated by Django 5.2.1 on 2025-06-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0005_rename_zipcode_authority_postal_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('authority', 'weekday', 'start_time', 'end_time')},
        ),
        migrations.AddField(
            model_name='timeslot',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='time_slots', to='authorities.doctor'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='services',
            field=models.ManyToManyField(related_name='time_slots', to='authorities.service'),
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='service',
        ),
    ]
