# Generated by Django 5.2.1 on 2025-06-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0006_alter_timeslot_unique_together_timeslot_doctors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='closing_time',
            field=models.TimeField(default='18:00', help_text='Closing time (24-hour format)'),
        ),
        migrations.AddField(
            model_name='authority',
            name='open_on_weekends',
            field=models.BooleanField(default=True, help_text='Check if open on weekends'),
        ),
        migrations.AddField(
            model_name='authority',
            name='opening_time',
            field=models.TimeField(default='09:00', help_text='Opening time (24-hour format)'),
        ),
    ]
