# Generated by Django 5.2.1 on 2025-06-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0007_authority_closing_time_authority_open_on_weekends_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='doctor',
        ),
        migrations.AddField(
            model_name='service',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='services', to='authorities.doctor'),
        ),
    ]
