# Generated by Django 5.1.7 on 2025-05-21 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('authorities', '0005_rename_zipcode_authority_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authority_appointments', to='authorities.authority'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='authorities.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_appointments', to='authorities.service'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authorities.timeslot'),
        ),
    ]
